### ISSUE TITLE
Review 5.1

### ISSUE THREAD

**Issue by fouticus** [CSU-R/Module1#8]
Hi Matt, take a look at 5.1, which is mostly complete, and give some thoughts if you have any.

**Comment by matthewross07** [comment]
I started reviewing 5.1 in my branch (mross). The major things I think we should discuss are: 

1) Should we keep the intros even more simple than you have defined them? Like should we just say you should always run
a single command on one line, and then skip all the semicolon stuff? 

2) I like how you introduce style early. 

3) Should we introduce grouped code here or later (as function intro or just in control_flow)? 

4) The tick marks like `x` in the bonus block make it unreadable. Maybe a css thing we have to change? 

5) State that almost all *commands* open and close with parentheses () other than calculator math and...? 

Otherwise I think this is super clean and really well done.
